#!/bin/bash

cat /proc/acpi/environ
cat /proc/buddyinfo/environ
cat /proc/bus/environ
cat /proc/cgroups/environ
cat /proc/cmdline/environ
cat /proc/consoles/environ
cat /proc/cpuinfo/environ
cat /proc/crypto/environ
cat /proc/devices/environ
cat /proc/diskstats/environ
cat /proc/dma/environ
cat /proc/driver/environ
cat /proc/dynamic_debug/environ
cat /proc/execdomains/environ
cat /proc/filesystems/environ
cat /proc/fs/environ
cat /proc/interrupts/environ
cat /proc/iomem/environ
cat /proc/ioports/environ
cat /proc/irq/environ
cat /proc/kallsyms/environ
cat /proc/kcore/environ
cat /proc/keys/environ
cat /proc/key-users/environ
cat /proc/kmsg/environ
cat /proc/kpagecgroup/environ
cat /proc/kpagecount/environ
cat /proc/kpageflags/environ
cat /proc/latency_stats/environ
cat /proc/loadavg/environ
cat /proc/locks/environ
cat /proc/mdstat/environ
cat /proc/meminfo/environ
cat /proc/misc/environ
cat /proc/modules/environ
cat /proc/self/mounts/environ
cat /proc/mtrr/environ
cat /proc/self/net/environ
cat /proc/pagetypeinfo/environ
cat /proc/partitions/environ
cat /proc/sched_debug/environ
cat /proc/schedstat/environ
cat /proc/118/environ
cat /proc/slabinfo/environ
cat /proc/softirqs/environ
cat /proc/stat/environ
cat /proc/swaps/environ
cat /proc/sys/environ
cat /proc/sysrq-trigger/environ
cat /proc/sysvipc/environ
cat /proc/118/task/118/environ
cat /proc/timer_list/environ
cat /proc/tty/environ
cat /proc/uptime/environ
cat /proc/version/environ
cat /proc/vmallocinfo/environ
cat /proc/vmstat/environ
cat /proc/zoneinfo/environ
